FROM nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install apt-utils git -y
RUN apt-get install python3.6 python3-dev python3-pip -y
RUN apt-get update

####################### Installing graspnet ####################################

WORKDIR /graspnet
RUN git clone https://github.com/graspnet/graspnet-baseline.git
WORKDIR /graspnet/graspnet-baseline
RUN pip3 install torch==1.6
#RUN pip3 install tensorboard==2.3
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install open3d==0.8
RUN python3 -m pip install --upgrade pip
RUN pip3 install Pillow
RUN pip3 install tqdm

WORKDIR /graspnet/graspnet-baseline/pointnet2
RUN python3 setup.py install
WORKDIR /graspnet/graspnet-baseline/knn
RUN python3 setup.py install

RUN apt-get install ffmpeg libsm6 libxext6  -y


WORKDIR /graspnetAPI
RUN git clone https://github.com/graspnet/graspnetAPI.git
WORKDIR /graspnetAPI//graspnetAPI
RUN pip3 install scikit-build
RUN pip3 install cython
RUN apt-get install libblas-dev liblapack-dev -y
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install graspnetAPI
WORKDIR /graspnet/graspnet-baseline/
COPY checkpoint-rs.tar .

#RUN rm /bin/sh && ln -s /bin/bash /bin/sh
